FROM quay.io/fedora/fedora-bootc:rawhide

RUN dnf install -y dnf5-plugins # for copr command
RUN dnf copr enable bipinbn/ignition-integration -y && dnf install -y ignition-integration

COPY ../builder/00-core.ign /usr/lib/dracut/modules.d/40ignition-conf/00-core.ign

# Commands 
RUN rm -v /usr/lib/systemd/system/local-fs.target.wants/bootc-generic-growpart.service
RUN systemctl mask systemd-repart.service

#### Configurations and Scripts
# Systemd presets are not evaluated if this exists.
# Switching to cosa osbuild should get rid of this?
# This file exists in the fedora-bootc image, but is empty.
RUN rm -r /etc/machine-id

#Finalize
# regenerate the initramfs
RUN set -xe; kver=$(ls /usr/lib/modules); env DRACUT_NO_XATTR=1 dracut -vf /usr/lib/modules/$kver/initramfs.img "$kver"

RUN cat > /usr/lib/bootc/install/10mount-spec.toml <<'EOF'
[install]
root-mount-spec = "LABEL=root"
EOF
