FROM quay.io/fedora/fedora-bootc:rawhide

RUN dnf install -y dnf5-plugins # for copr command
RUN dnf copr enable bipinbn/ignition-integration -y && dnf install -y ignition-integration

RUN cat > /usr/lib/dracut//modules.d/40ignition-conf/00-core.ign <<'EOF'
{
  "ignition": {
    "version": "3.0.0"
  },
  "passwd": {
    "users": [
      {
        "name": "admin",
        "gecos": "Administrator user",
        "groups": [
          "wheel",
          "adm",
          "systemd-journal"
        ]
      }
    ]
  }
}
EOF

# Commands 
RUN rm -v /usr/lib/systemd/system/local-fs.target.wants/bootc-generic-growpart.service
RUN systemctl mask systemd-repart.service

#### Configurations and Scripts
# sudoers.d.
# passwordless sudo for  %sudo and %wheel
COPY ../conf/sudoers.d/passwordless-sudo /etc/sudoers.d/passwordless-sudo
RUN chmod 440 /etc/sudoers.d/passwordless-sudo

# Systemd presets are not evaluated if this exists.
# Switching to cosa osbuild should get rid of this?
# This file exists in the fedora-bootc image, but is empty.
RUN rm -r /etc/machine-id

#Finalize
# regenerate the initramfs
RUN set -xe; kver=$(ls /usr/lib/modules); env DRACUT_NO_XATTR=1 dracut -vf /usr/lib/modules/$kver/initramfs.img "$kver"

RUN cat > /usr/lib/bootc/install/10mount-spec.toml <<'EOF'
[install]
root-mount-spec = "LABEL=root"
EOF
